name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  jupyter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy Pipfile
        run: cp ./Pipfile ./jupyter/Pipfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "./jupyter/"
          push: true
          tags: nevedomski/doc-qa-jupyter:latest
